services:
  - type: web
    name: smart-energy-monitor

    env: python   # ✅ use this instead

    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13   # ✅ exact version

      - key: DATABASE_URL
        fromDatabase:
          name: smart-energy-db
          property: connectionString

databases:
  - name: smart-energy-db
    databaseName: smart_energy
    user: smart_energy_user
